package site.coreservice.product.infrastructure.seed;

import java.util.List;
import site.coreservice.product.domain.PressType;

/**
 * 로컬 데모용 상품·아티스트 시드 원장. 로더(ProductSeedLoader)의 절차와 데이터를 분리해,
 * 데이터를 늘릴 때 이 파일만 고치면 되게 한다.
 * <p>
 * 카탈로그번호는 유명 음반은 실제 번호를 썼고, 실물 LP가 확실치 않은 음반(최신 K-pop 등)은
 * 그럴듯하게 지어낸 데모용 값이다 — 검색·시세 화면 시연이 목적이라 실물 정확성은 요구하지 않는다.
 * 같은 번호가 두 번 나오면 자연키가 겹쳐 뒤의 상품이 조용히 앞의 상품으로 합쳐지므로,
 * 번호 중복은 테스트(ProductSeedDataTest)가 막는다.
 * <p>
 * basePrice는 시세 시드(PriceHistorySeedLoader)가 쓰는 기준 낙찰가(NEAR_MINT 기준, 원)다.
 * 값이 있으면 그 상품에 시세 기록이 쌓이고, null이면 시세 없이 남는다 —
 * "거래 없음 = 200 + 빈 배열" 응답도 시연해야 하므로 일부는 반드시 null로 남겨둔다 (테스트가 지킨다).
 */
final class ProductSeedData {

    record ArtistSeed(String name, List<String> aliases) {
    }

    record ProductSeed(String catalogNumber, String artistName, String title, List<String> titleAliases,
            String releaseCountry, int releaseYear, PressType pressType, String format, String label,
            String genre, String description, Long basePrice) {
    }

    static final List<ArtistSeed> ARTISTS = List.of(
            // 한국 — 고전
            new ArtistSeed("김광석", List.of("Kim Kwangseok")),
            new ArtistSeed("산울림", List.of("Sanullim")),
            new ArtistSeed("조용필", List.of("Cho Yong-pil")),
            new ArtistSeed("신중현", List.of("Shin Joong Hyun")),
            new ArtistSeed("유재하", List.of("Yoo Jae-ha")),
            new ArtistSeed("김현식", List.of("Kim Hyun-sik")),
            new ArtistSeed("들국화", List.of("Deulgukhwa")),
            new ArtistSeed("이문세", List.of("Lee Moon-sae")),
            new ArtistSeed("김추자", List.of("Kim Choo-ja")),
            new ArtistSeed("한대수", List.of("Hahn Dae-soo")),
            new ArtistSeed("김민기", List.of("Kim Min-ki")),
            new ArtistSeed("서태지와 아이들", List.of("서태지", "Seo Taiji and Boys")),
            // 한국 — 현역·K-pop
            new ArtistSeed("아이유", List.of("IU")),
            new ArtistSeed("방탄소년단", List.of("BTS")),
            new ArtistSeed("블랙핑크", List.of("BLACKPINK")),
            new ArtistSeed("NewJeans", List.of("뉴진스")),
            new ArtistSeed("aespa", List.of("에스파")),
            new ArtistSeed("IVE", List.of("아이브")),
            new ArtistSeed("세븐틴", List.of("SEVENTEEN")),
            new ArtistSeed("빅뱅", List.of("BIGBANG")),
            new ArtistSeed("소녀시대", List.of("Girls' Generation")),
            new ArtistSeed("잔나비", List.of("Jannabi")),
            new ArtistSeed("혁오", List.of("HYUKOH")),
            new ArtistSeed("검정치마", List.of("The Black Skirts")),
            new ArtistSeed("장기하와 얼굴들", List.of("장기하")),
            // 해외 — 클래식 록·팝
            new ArtistSeed("The Beatles", List.of("비틀즈", "Beatles")),
            new ArtistSeed("Pink Floyd", List.of("핑크 플로이드")),
            new ArtistSeed("Led Zeppelin", List.of("레드 제플린")),
            new ArtistSeed("Queen", List.of("퀸")),
            new ArtistSeed("David Bowie", List.of("데이비드 보위")),
            new ArtistSeed("The Rolling Stones", List.of("롤링 스톤스")),
            new ArtistSeed("Bob Dylan", List.of("밥 딜런")),
            new ArtistSeed("Fleetwood Mac", List.of("플리트우드 맥")),
            new ArtistSeed("Eagles", List.of("이글스")),
            new ArtistSeed("Metallica", List.of("메탈리카")),
            new ArtistSeed("Nirvana", List.of("너바나")),
            new ArtistSeed("Oasis", List.of("오아시스")),
            new ArtistSeed("Radiohead", List.of("라디오헤드")),
            new ArtistSeed("Coldplay", List.of("콜드플레이")),
            new ArtistSeed("Michael Jackson", List.of("마이클 잭슨")),
            new ArtistSeed("Prince", List.of("프린스")),
            new ArtistSeed("Madonna", List.of("마돈나")),
            // 해외 — 재즈
            new ArtistSeed("Miles Davis", List.of("마일스 데이비스")),
            new ArtistSeed("John Coltrane", List.of("존 콜트레인")),
            new ArtistSeed("Bill Evans", List.of("빌 에반스")),
            // 해외 — 2000년대 이후
            new ArtistSeed("Daft Punk", List.of("다프트 펑크")),
            new ArtistSeed("Taylor Swift", List.of("테일러 스위프트")),
            new ArtistSeed("Adele", List.of("아델")),
            new ArtistSeed("Billie Eilish", List.of("빌리 아일리시")),
            new ArtistSeed("Olivia Rodrigo", List.of("올리비아 로드리고")),
            new ArtistSeed("The Weeknd", List.of("위켄드")),
            new ArtistSeed("Kendrick Lamar", List.of("켄드릭 라마")),
            new ArtistSeed("Dua Lipa", List.of("두아 리파")),
            new ArtistSeed("Harry Styles", List.of("해리 스타일스")));

    static final List<ProductSeed> PRODUCTS = List.of(
            // ── The Beatles / Pink Floyd / Miles Davis — 초기 시드 유지분 (자연키 변경 금지: 기존 로컬 DB와 이어짐)
            new ProductSeed("PCS 7088", "The Beatles", "Abbey Road", List.of("애비 로드"), "UK", 1969,
                    PressType.ORIGINAL, "LP", "Apple Records", "Rock", "1969년 영국 오리지널 프레싱", 350_000L),
            new ProductSeed("0602577915096", "The Beatles", "Abbey Road", List.of("애비 로드"), "UK", 2019,
                    PressType.REISSUE, "180g", "Apple Records", "Rock", "2019년 50주년 리마스터 리이슈", null),
            new ProductSeed("SHVL 804", "Pink Floyd", "The Dark Side of the Moon", List.of("다크 사이드 오브 더 문"),
                    "UK", 1973, PressType.ORIGINAL, "LP", "Harvest", "Progressive Rock", "1973년 영국 오리지널 프레싱",
                    280_000L),
            new ProductSeed("PFRLP8", "Pink Floyd", "The Dark Side of the Moon", List.of("다크 사이드 오브 더 문"),
                    "Europe", 2016, PressType.REISSUE, "180g", "Pink Floyd Records", "Progressive Rock",
                    "2016년 리마스터 리이슈", null),
            new ProductSeed("CL 1355", "Miles Davis", "Kind of Blue", List.of("카인드 오브 블루"), "US", 1959,
                    PressType.ORIGINAL, "LP", "Columbia", "Jazz", "1959년 미국 오리지널 프레싱", 800_000L),
            new ProductSeed(null, "The Beatles", "Kum Back", List.of("컴 백"), "US", 1969,
                    PressType.ORIGINAL, "LP", null, "Rock", "겟 백 세션 부틀렉 — 카탈로그번호 없는 음반 예시", null),
            new ProductSeed("PCS 7096", "The Beatles", "Let It Be", List.of("렛 잇 비"), "UK", 1970,
                    PressType.ORIGINAL, "LP", "Apple Records", "Rock", "1970년 영국 오리지널 프레싱", 320_000L),
            new ProductSeed("GP 26", "Miles Davis", "Bitches Brew", List.of("비치스 브루"), "US", 1970,
                    PressType.ORIGINAL, "LP", "Columbia", "Jazz", "1970년 미국 오리지널 프레싱, 게이트폴드 2LP",
                    250_000L),
            new ProductSeed("PMC 7027", "The Beatles", "Sgt. Pepper's Lonely Hearts Club Band", List.of(),
                    "UK", 1967, PressType.ORIGINAL, "LP", "Parlophone", "Rock", "1967년 영국 모노 오리지널 프레싱",
                    450_000L),
            new ProductSeed("PCS 7009", "The Beatles", "Revolver", List.of("리볼버"), "UK", 1966,
                    PressType.ORIGINAL, "LP", "Parlophone", "Rock", "1966년 영국 오리지널 프레싱", 380_000L),
            new ProductSeed("SHVL 814", "Pink Floyd", "Wish You Were Here", List.of(), "UK", 1975,
                    PressType.ORIGINAL, "LP", "Harvest", "Progressive Rock", "1975년 영국 오리지널 프레싱", 260_000L),
            new ProductSeed("SHDW 411", "Pink Floyd", "The Wall", List.of("더 월"), "UK", 1979,
                    PressType.ORIGINAL, "2LP", "Harvest", "Progressive Rock", "1979년 영국 오리지널 프레싱", 180_000L),
            new ProductSeed("CL 1480", "Miles Davis", "Sketches of Spain", List.of(), "US", 1960,
                    PressType.ORIGINAL, "LP", "Columbia", "Jazz", "1960년 미국 오리지널 프레싱", 220_000L),
            // ── 해외 클래식 록
            new ProductSeed("SD 7208", "Led Zeppelin", "Led Zeppelin IV", List.of("레드 제플린 4집"), "US", 1971,
                    PressType.ORIGINAL, "LP", "Atlantic", "Rock", "1971년 미국 오리지널 프레싱", 300_000L),
            new ProductSeed("SD 8236", "Led Zeppelin", "Led Zeppelin II", List.of(), "US", 1969,
                    PressType.ORIGINAL, "LP", "Atlantic", "Rock", "1969년 미국 오리지널 프레싱", 280_000L),
            new ProductSeed("SS 2-200", "Led Zeppelin", "Physical Graffiti", List.of(), "US", 1975,
                    PressType.ORIGINAL, "2LP", "Swan Song", "Rock", "1975년 미국 오리지널 프레싱", null),
            new ProductSeed("EMTC 103", "Queen", "A Night at the Opera", List.of("오페라의 밤"), "UK", 1975,
                    PressType.ORIGINAL, "LP", "EMI", "Rock", "1975년 영국 오리지널 프레싱", 270_000L),
            new ProductSeed("EMA 784", "Queen", "News of the World", List.of(), "UK", 1977,
                    PressType.ORIGINAL, "LP", "EMI", "Rock", "1977년 영국 오리지널 프레싱", null),
            new ProductSeed("EMTV 30", "Queen", "Greatest Hits", List.of(), "UK", 1981,
                    PressType.ORIGINAL, "LP", "EMI", "Rock", "1981년 영국 오리지널 프레싱", null),
            new ProductSeed("SF 8287", "David Bowie", "The Rise and Fall of Ziggy Stardust and the Spiders from Mars",
                    List.of("지기 스타더스트"), "UK", 1972, PressType.ORIGINAL, "LP", "RCA", "Rock",
                    "1972년 영국 오리지널 프레싱", 330_000L),
            new ProductSeed("PL 12030", "David Bowie", "Low", List.of(), "UK", 1977,
                    PressType.ORIGINAL, "LP", "RCA", "Rock", "1977년 영국 오리지널 프레싱, 베를린 3부작 1편", null),
            new ProductSeed("COC 59100", "The Rolling Stones", "Sticky Fingers", List.of(), "UK", 1971,
                    PressType.ORIGINAL, "LP", "Rolling Stones Records", "Rock", "1971년 영국 오리지널 프레싱, 지퍼 커버",
                    240_000L),
            new ProductSeed("COC 69100", "The Rolling Stones", "Exile on Main St.", List.of(), "UK", 1972,
                    PressType.ORIGINAL, "2LP", "Rolling Stones Records", "Rock", "1972년 영국 오리지널 프레싱",
                    210_000L),
            new ProductSeed("CL 2389", "Bob Dylan", "Highway 61 Revisited", List.of(), "US", 1965,
                    PressType.ORIGINAL, "LP", "Columbia", "Folk Rock", "1965년 미국 오리지널 프레싱", 350_000L),
            new ProductSeed("PC 33235", "Bob Dylan", "Blood on the Tracks", List.of(), "US", 1975,
                    PressType.ORIGINAL, "LP", "Columbia", "Folk Rock", "1975년 미국 오리지널 프레싱", 180_000L),
            new ProductSeed("BSK 3010", "Fleetwood Mac", "Rumours", List.of("루머스"), "US", 1977,
                    PressType.ORIGINAL, "LP", "Warner Bros.", "Rock", "1977년 미국 오리지널 프레싱", 200_000L),
            new ProductSeed("6E-103", "Eagles", "Hotel California", List.of("호텔 캘리포니아"), "US", 1976,
                    PressType.ORIGINAL, "LP", "Asylum", "Rock", "1976년 미국 오리지널 프레싱", 230_000L),
            new ProductSeed("60439-1", "Metallica", "Master of Puppets", List.of(), "US", 1986,
                    PressType.ORIGINAL, "LP", "Elektra", "Metal", "1986년 미국 오리지널 프레싱", 170_000L),
            new ProductSeed("61113-1", "Metallica", "Metallica", List.of("블랙 앨범"), "US", 1991,
                    PressType.ORIGINAL, "2LP", "Elektra", "Metal", "1991년 미국 오리지널 프레싱", null),
            new ProductSeed("DGC-24425", "Nirvana", "Nevermind", List.of("네버마인드"), "US", 1991,
                    PressType.ORIGINAL, "LP", "DGC", "Rock", "1991년 미국 오리지널 프레싱", 180_000L),
            new ProductSeed("GEF-24607", "Nirvana", "In Utero", List.of("인 유테로"), "US", 1993,
                    PressType.ORIGINAL, "LP", "Geffen", "Rock", "1993년 미국 오리지널 프레싱", 150_000L),
            new ProductSeed("DGC-24727", "Nirvana", "MTV Unplugged in New York", List.of(), "US", 1994,
                    PressType.ORIGINAL, "LP", "DGC", "Rock", "1994년 미국 오리지널 프레싱", null),
            new ProductSeed("CRE LP 189", "Oasis", "(What's the Story) Morning Glory?", List.of(), "UK", 1995,
                    PressType.ORIGINAL, "2LP", "Creation", "Rock", "1995년 영국 오리지널 프레싱", null),
            new ProductSeed("NODATA 02", "Radiohead", "OK Computer", List.of("오케이 컴퓨터"), "UK", 1997,
                    PressType.ORIGINAL, "2LP", "Parlophone", "Rock", "1997년 영국 오리지널 프레싱", 190_000L),
            new ProductSeed("KIDA 1", "Radiohead", "Kid A", List.of(), "UK", 2000,
                    PressType.ORIGINAL, "2LP", "Parlophone", "Rock", "2000년 영국 오리지널 프레싱", null),
            new ProductSeed("XLLP 324", "Radiohead", "In Rainbows", List.of("인 레인보우즈"), "UK", 2007,
                    PressType.ORIGINAL, "LP", "XL Recordings", "Rock", "2007년 영국 오리지널 프레싱", 170_000L),
            new ProductSeed("527783 1", "Coldplay", "Parachutes", List.of(), "UK", 2000,
                    PressType.ORIGINAL, "LP", "Parlophone", "Rock", "2000년 영국 오리지널 프레싱", null),
            new ProductSeed("0190296666964", "Coldplay", "Music of the Spheres", List.of(), "UK", 2021,
                    PressType.ORIGINAL, "180g", "Parlophone", "Pop Rock", "2021년 발매", null),
            // ── 해외 팝·R&B·힙합
            new ProductSeed("FE 35745", "Michael Jackson", "Off the Wall", List.of(), "US", 1979,
                    PressType.ORIGINAL, "LP", "Epic", "Pop", "1979년 미국 오리지널 프레싱", null),
            new ProductSeed("QE 38112", "Michael Jackson", "Thriller", List.of("스릴러"), "US", 1982,
                    PressType.ORIGINAL, "LP", "Epic", "Pop", "1982년 미국 오리지널 프레싱", 210_000L),
            new ProductSeed("E 40600", "Michael Jackson", "Bad", List.of("배드"), "US", 1987,
                    PressType.ORIGINAL, "LP", "Epic", "Pop", "1987년 미국 오리지널 프레싱", null),
            new ProductSeed("25110-1", "Prince", "Purple Rain", List.of("퍼플 레인"), "US", 1984,
                    PressType.ORIGINAL, "LP", "Warner Bros.", "Pop", "1984년 미국 오리지널 프레싱", 200_000L),
            new ProductSeed("25157-1", "Madonna", "Like a Virgin", List.of(), "US", 1984,
                    PressType.ORIGINAL, "LP", "Sire", "Pop", "1984년 미국 오리지널 프레싱", null),
            new ProductSeed("B0031929-01", "The Weeknd", "After Hours", List.of("애프터 아워스"), "US", 2020,
                    PressType.ORIGINAL, "2LP", "XO", "R&B", "2020년 발매", null),
            new ProductSeed("B0026141-01", "The Weeknd", "Starboy", List.of("스타보이"), "US", 2016,
                    PressType.ORIGINAL, "2LP", "XO", "R&B", "2016년 발매", null),
            new ProductSeed("B0035472-01", "The Weeknd", "Dawn FM", List.of("던 FM"), "US", 2022,
                    PressType.ORIGINAL, "2LP", "XO", "R&B", "2022년 발매", null),
            new ProductSeed("B0022958-01", "Kendrick Lamar", "To Pimp a Butterfly", List.of("투 핌프 어 버터플라이"),
                    "US", 2015, PressType.ORIGINAL, "2LP", "Top Dawg", "Hip-Hop", "2015년 발매", 120_000L),
            new ProductSeed("B0026716-01", "Kendrick Lamar", "DAMN.", List.of("댐"), "US", 2017,
                    PressType.ORIGINAL, "LP", "Top Dawg", "Hip-Hop", "2017년 발매", 80_000L),
            // ── 해외 재즈
            new ProductSeed("BLP 1577", "John Coltrane", "Blue Train", List.of("블루 트레인"), "US", 1958,
                    PressType.ORIGINAL, "LP", "Blue Note", "Jazz", "1958년 미국 오리지널 프레싱", 600_000L),
            new ProductSeed("AS-77", "John Coltrane", "A Love Supreme", List.of("어 러브 수프림"), "US", 1965,
                    PressType.ORIGINAL, "LP", "Impulse!", "Jazz", "1965년 미국 오리지널 프레싱", 400_000L),
            new ProductSeed("RLP-9376", "Bill Evans", "Sunday at the Village Vanguard", List.of(), "US", 1961,
                    PressType.ORIGINAL, "LP", "Riverside", "Jazz", "1961년 미국 오리지널 프레싱", 350_000L),
            new ProductSeed("RLP-9399", "Bill Evans", "Waltz for Debby", List.of("왈츠 포 데비"), "US", 1962,
                    PressType.ORIGINAL, "LP", "Riverside", "Jazz", "1962년 미국 오리지널 프레싱", 450_000L),
            // ── 해외 2000년대 이후·최신
            new ProductSeed("V2940", "Daft Punk", "Discovery", List.of("디스커버리"), "UK", 2001,
                    PressType.ORIGINAL, "2LP", "Virgin", "Electronic", "2001년 발매", null),
            new ProductSeed("88883716861", "Daft Punk", "Random Access Memories", List.of("랜덤 액세스 메모리즈"),
                    "US", 2013, PressType.ORIGINAL, "2LP", "Columbia", "Electronic", "2013년 발매", 120_000L),
            new ProductSeed("B0032914-01", "Taylor Swift", "Folklore", List.of("포크로어"), "US", 2020,
                    PressType.ORIGINAL, "2LP", "Republic", "Pop", "2020년 발매", 90_000L),
            new ProductSeed("B0036553-01", "Taylor Swift", "Midnights", List.of("미드나이츠"), "US", 2022,
                    PressType.ORIGINAL, "LP", "Republic", "Pop", "2022년 발매", 70_000L),
            new ProductSeed("B0038899-01", "Taylor Swift", "1989 (Taylor's Version)", List.of(), "US", 2023,
                    PressType.ORIGINAL, "2LP", "Republic", "Pop", "2023년 재녹음반", 85_000L),
            new ProductSeed("B0039891-01", "Taylor Swift", "The Tortured Poets Department", List.of(), "US", 2024,
                    PressType.ORIGINAL, "2LP", "Republic", "Pop", "2024년 발매", null),
            new ProductSeed("XLLP 520", "Adele", "21", List.of(), "UK", 2011,
                    PressType.ORIGINAL, "LP", "XL Recordings", "Pop", "2011년 발매", 80_000L),
            new ProductSeed("194399855812", "Adele", "30", List.of(), "UK", 2021,
                    PressType.ORIGINAL, "2LP", "Columbia", "Pop", "2021년 발매", null),
            new ProductSeed("B0033832-01", "Billie Eilish", "Happier Than Ever", List.of("해피어 댄 에버"),
                    "US", 2021, PressType.ORIGINAL, "2LP", "Interscope", "Pop", "2021년 발매", 75_000L),
            new ProductSeed("B0039742-01", "Billie Eilish", "Hit Me Hard and Soft", List.of(), "US", 2024,
                    PressType.ORIGINAL, "LP", "Interscope", "Pop", "2024년 발매", null),
            new ProductSeed("B0033897-01", "Olivia Rodrigo", "SOUR", List.of("사워"), "US", 2021,
                    PressType.ORIGINAL, "LP", "Geffen", "Pop", "2021년 발매", 70_000L),
            new ProductSeed("B0038163-01", "Olivia Rodrigo", "GUTS", List.of("거츠"), "US", 2023,
                    PressType.ORIGINAL, "LP", "Geffen", "Pop", "2023년 발매", null),
            new ProductSeed("0190295939526", "Dua Lipa", "Future Nostalgia", List.of("퓨처 노스탤지어"), "UK", 2020,
                    PressType.ORIGINAL, "LP", "Warner", "Pop", "2020년 발매", 65_000L),
            new ProductSeed("19439985641", "Harry Styles", "Harry's House", List.of("해리스 하우스"), "UK", 2022,
                    PressType.ORIGINAL, "LP", "Columbia", "Pop", "2022년 발매", 70_000L),
            // ── 한국 고전
            new ProductSeed("SR-0107", "산울림", "산울림 새노래 모음", List.of("아니 벌써"), "Korea", 1977,
                    PressType.ORIGINAL, "LP", "서라벌레코드", "Rock", "1977년 한국 오리지널 프레싱, 산울림 1집",
                    550_000L),
            new ProductSeed("SR-0121", "산울림", "산울림 2집", List.of("내 마음에 주단을 깔고"), "Korea", 1978,
                    PressType.ORIGINAL, "LP", "서라벌레코드", "Rock", "1978년 한국 오리지널 프레싱", 480_000L),
            new ProductSeed("SKC 1089", "김광석", "다시 부르기", List.of("다시부르기 1"), "Korea", 1993,
                    PressType.ORIGINAL, "LP", "킹레코드", "Folk", "1993년 한국 오리지널 프레싱", 250_000L),
            new ProductSeed("SKC 1095", "김광석", "다시 부르기 II", List.of("다시부르기 2"), "Korea", 1995,
                    PressType.ORIGINAL, "LP", "킹레코드", "Folk", "1995년 한국 오리지널 프레싱", null),
            new ProductSeed("JLS-120986", "조용필", "창밖의 여자", List.of("조용필 1집"), "Korea", 1980,
                    PressType.ORIGINAL, "LP", "지구레코드", "Pop", "1980년 한국 오리지널 프레싱, 조용필 1집",
                    300_000L),
            new ProductSeed("JLS-1202301", "조용필", "미지의 세계", List.of("여행을 떠나요"), "Korea", 1985,
                    PressType.ORIGINAL, "LP", "지구레코드", "Pop", "1985년 한국 오리지널 프레싱, 조용필 7집",
                    260_000L),
            new ProductSeed("JLS-120786", "신중현", "신중현과 엽전들 1집", List.of("미인"), "Korea", 1974,
                    PressType.ORIGINAL, "LP", "지구레코드", "Rock", "1974년 한국 오리지널 프레싱", 700_000L),
            new ProductSeed("SPDR-165", "유재하", "사랑하기 때문에", List.of(), "Korea", 1987,
                    PressType.ORIGINAL, "LP", "서울음반", "Ballad", "1987년 한국 오리지널 프레싱, 유일한 정규작",
                    650_000L),
            new ProductSeed("KINGLP-1701", "유재하", "사랑하기 때문에", List.of(), "Korea", 2017,
                    PressType.REISSUE, "180g", "킹레코드", "Ballad", "2017년 30주년 기념 리이슈", 90_000L),
            new ProductSeed("SPDR-138", "김현식", "김현식 III", List.of("비처럼 음악처럼"), "Korea", 1986,
                    PressType.ORIGINAL, "LP", "서울음반", "Ballad", "1986년 한국 오리지널 프레싱", 280_000L),
            new ProductSeed("SR-0173", "들국화", "들국화", List.of("행진"), "Korea", 1985,
                    PressType.ORIGINAL, "LP", "서라벌레코드", "Rock", "1985년 한국 오리지널 프레싱, 들국화 1집",
                    400_000L),
            new ProductSeed("KSC-1287", "이문세", "이문세 4집", List.of("사랑이 지나가면"), "Korea", 1987,
                    PressType.ORIGINAL, "LP", "킹레코드", "Ballad", "1987년 한국 오리지널 프레싱", 220_000L),
            new ProductSeed("KLS-15", "김추자", "늦기전에", List.of(), "Korea", 1969,
                    PressType.ORIGINAL, "LP", "킹레코드", "Soul", "1969년 한국 오리지널 프레싱, 신중현 프로듀스",
                    750_000L),
            new ProductSeed("JLS-120475", "한대수", "고무신", List.of("멋진 그대"), "Korea", 1975,
                    PressType.ORIGINAL, "LP", "지구레코드", "Folk Rock", "1975년 한국 오리지널 프레싱", 500_000L),
            new ProductSeed("DG-1004", "김민기", "김민기", List.of("아침이슬"), "Korea", 1971,
                    PressType.ORIGINAL, "LP", "대도레코드", "Folk", "1971년 한국 오리지널 프레싱", 850_000L),
            new ProductSeed("BDL-0128", "서태지와 아이들", "서태지와 아이들", List.of("난 알아요"), "Korea", 1992,
                    PressType.ORIGINAL, "LP", "반도음반", "K-Pop", "1992년 한국 오리지널 프레싱, 데뷔작", 180_000L),
            new ProductSeed("BDL-0165", "서태지와 아이들", "서태지와 아이들 II", List.of("하여가"), "Korea", 1993,
                    PressType.ORIGINAL, "LP", "반도음반", "K-Pop", "1993년 한국 오리지널 프레싱", null),
            // ── 한국 현역·K-pop (실물 LP가 확실치 않은 음반은 데모용 가상 카탈로그번호)
            new ProductSeed("L200002171", "아이유", "Palette", List.of("팔레트"), "Korea", 2017,
                    PressType.ORIGINAL, "LP", "카카오엔터테인먼트", "K-Pop", "2017년 발매", 120_000L),
            new ProductSeed("L100005825", "아이유", "조각집", List.of("Pieces"), "Korea", 2021,
                    PressType.ORIGINAL, "LP", "EDAM엔터테인먼트", "K-Pop", "2021년 발매", null),
            new ProductSeed("HYBE-BE01", "방탄소년단", "BE", List.of(), "Korea", 2021,
                    PressType.ORIGINAL, "LP", "빅히트뮤직", "K-Pop", "2021년 발매", null),
            new ProductSeed("HYBE-PF22", "방탄소년단", "Proof", List.of("프루프"), "Korea", 2022,
                    PressType.ORIGINAL, "LP", "빅히트뮤직", "K-Pop", "2022년 발매", null),
            new ProductSeed("YGLP-2020", "블랙핑크", "THE ALBUM", List.of("더 앨범"), "Korea", 2020,
                    PressType.ORIGINAL, "LP", "YG엔터테인먼트", "K-Pop", "2020년 발매", 95_000L),
            new ProductSeed("ADOR-001", "NewJeans", "New Jeans", List.of("뉴진스 1st EP"), "Korea", 2022,
                    PressType.ORIGINAL, "LP", "ADOR", "K-Pop", "2022년 발매, 데뷔 EP", null),
            new ProductSeed("ADOR-002", "NewJeans", "Get Up", List.of("겟 업"), "Korea", 2023,
                    PressType.ORIGINAL, "LP", "ADOR", "K-Pop", "2023년 발매", 80_000L),
            new ProductSeed("SMLP-1201", "aespa", "Armageddon", List.of("아마겟돈"), "Korea", 2024,
                    PressType.ORIGINAL, "LP", "SM엔터테인먼트", "K-Pop", "2024년 발매", null),
            new ProductSeed("SLP-0223", "IVE", "I've IVE", List.of("아이브 1집"), "Korea", 2023,
                    PressType.ORIGINAL, "LP", "스타쉽엔터테인먼트", "K-Pop", "2023년 발매", null),
            new ProductSeed("PLD-8231", "세븐틴", "FML", List.of(), "Korea", 2023,
                    PressType.ORIGINAL, "LP", "플레디스엔터테인먼트", "K-Pop", "2023년 발매", null),
            new ProductSeed("YGLP-1601", "빅뱅", "MADE", List.of("메이드"), "Korea", 2016,
                    PressType.ORIGINAL, "LP", "YG엔터테인먼트", "K-Pop", "2016년 발매", null),
            new ProductSeed("SMLP-2207", "소녀시대", "FOREVER 1", List.of("포에버 원"), "Korea", 2022,
                    PressType.ORIGINAL, "LP", "SM엔터테인먼트", "K-Pop", "2022년 발매, 데뷔 15주년 기념반", null),
            new ProductSeed("PEPONI-1901", "잔나비", "전설", List.of("주저하는 연인들을 위해"), "Korea", 2019,
                    PressType.ORIGINAL, "LP", "페포니뮤직", "Rock", "2019년 발매", null),
            new ProductSeed("HYUK-2014", "혁오", "20", List.of(), "Korea", 2014,
                    PressType.ORIGINAL, "LP", null, "Rock", "2014년 발매, 데뷔 EP", null),
            new ProductSeed("HIGHGRND-002", "혁오", "23", List.of(), "Korea", 2017,
                    PressType.ORIGINAL, "LP", "하이그라운드", "Rock", "2017년 발매", null),
            new ProductSeed("DGDM-201", "검정치마", "201", List.of(), "Korea", 2011,
                    PressType.ORIGINAL, "LP", null, "Rock", "2011년 발매", null),
            new ProductSeed("BGBG-0901", "장기하와 얼굴들", "별일 없이 산다", List.of("싸구려 커피"), "Korea", 2009,
                    PressType.ORIGINAL, "LP", "붕가붕가레코드", "Rock", "2009년 발매, 1집", null));

    private ProductSeedData() {
    }
}
