plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common')

    // Web
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'

    // 관측이 붙은 RestClient.Builder 오토컨피규레이션 (AuctionClientConfig 트레이스 전파에 필요)
    implementation 'org.springframework.boot:spring-boot-starter-restclient'

    // JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // MySQL
    runtimeOnly 'com.mysql:mysql-connector-j'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'

    // Redis / Redisson 추가
    // Spring Boot 공식 BOM에 포함되지 않는 외부 라이브러리이므로 버전 명시 필요 (spring boot 4 => 4.x.y버전)
    implementation 'org.redisson:redisson-spring-boot-starter:4.7.0'

    // AOP (분산락 어노테이션 - @Aspect 처리를 위해 필요)
    // Spring Boot 4부터 spring-boot-starter-aop가 없어져서(4.0.0-M2까지만 존재) aspectjweaver를 직접 추가한다.
    // 버전은 Spring Boot BOM이 관리하므로 명시하지 않는다.
    implementation 'org.aspectj:aspectjweaver'

    // H2 (테스트)
    testRuntimeOnly 'com.h2database:h2'

    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // AOP
    implementation 'org.springframework.boot:spring-boot-starter-aspectj'       // spring boot 4.1.0 이후

    // resilience4j
    implementation 'io.github.resilience4j:resilience4j-spring-boot4:2.4.0'     // spring boot4
    implementation 'org.apache.httpcomponents.client5:httpclient5'

    // AWS S3 (이미지 업로드 PresignedUrl 발급)
    implementation platform('software.amazon.awssdk:bom:2.53.2')
    implementation 'software.amazon.awssdk:s3'
}

tasks.named('jar') {
    enabled = false
}

bootJar {
    archiveFileName = 'auction-service.jar'
}
