server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:33340/member_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none

app:
  jwt:
    access-token-secret-key: YWNjZXNzLXRva2VuLXNlY3JldC1rZXktZm9yLWxvY2FsLWRldmVsb3BtZW50LWVudmlyb25tZW50MTIzNA==
    refresh-token-secret-key: cmVmcmVzaC10b2tlbi1zZWNyZXQta2V5LWZvci1sb2NhbC1kZXZlbG9wbWVudC1lbnZpcm9ubWVudDEyMzQ=
    access-token-expiration-time: 1200000 # 20분
    refresh-token-expiration-time: 604800000 # 7일

KAFKA_BOOTSTRAP_SERVERS: localhost:9092
