server:
  port: 8081
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  Jackson:
    mapper:
      SORT_PROPERTIES_ALPHABETICALLY: false

  application:
    name: member-service

  profiles:
    active: local

  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
      base-path: /api/actuator