PORT_NUMBER: 8080
MEMBER_SERVICE_URI: http://localhost:8081
FULFILLMENT_SERVICE_URI: http://localhost:8083
PRODUCT_SERVICE_URI: http://localhost:8084
AUCTION_SERVICE_URI: http://localhost:8085
POINTWALLET_SERVICE_URI: http://localhost:8086
JWT_SECRET_KEY: c2VjcmV0LWtleS1mb3ItbG9jYWwtZGV2ZWxvcG1lbnQtZW52aXJvbm1lbnQxMjM0NTY3ODkw
JWT_EXPIRATION_TIME: 3600000
