server:
  port: ${PORT_NUMBER}
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  Jackson:
    mapper:
      SORT_PROPERTIES_ALPHABETICALLY: false

  application:
    name: product-service

  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        enable.idempotence: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.trusted.packages: site.common.event.contract
    listener:
      ack-mode: batch

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
      base-path: /product-service/actuator
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:0.15}
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${TEMPO_OTLP_ENDPOINT:http://localhost:4318/v1/traces}
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

product:
  auction-api:
    base-url: ${AUCTION_SERVICE_BASE_URL}
