plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common')

    // Web
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'

    // JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // MySQL
    runtimeOnly 'com.mysql:mysql-connector-j'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'

    // Spring Security Crypto
    implementation 'org.springframework.security:spring-security-crypto'

    // BouncyCastle
    implementation 'org.bouncycastle:bcprov-jdk18on:1.84'

    // JWT
    implementation("io.jsonwebtoken:jjwt-api:0.12.7")
    implementation("io.jsonwebtoken:jjwt-impl:0.12.7")
    runtimeOnly("io.jsonwebtoken:jjwt-gson:0.12.7")
}
