plugins {
    id 'org.springframework.boot'
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.ai:spring-ai-bom:2.0.0'
    }
}

dependencies {
    implementation project(':common')

    // Web
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'

    // Elasticsearch
    implementation 'org.springframework.boot:spring-boot-starter-data-elasticsearch'

    // OpenAI
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'
}

tasks.named('jar') {
    enabled = false
}

bootJar {
    archiveFileName = 'exploration-service.jar'
}
