spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33340/lp_auction
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
