server:
  port: ${PORT_NUMBER}
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  Jackson:
    mapper:
      SORT_PROPERTIES_ALPHABETICALLY: false

  application:
    name: core-service

  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
      base-path: /api/actuator

toss:
  payments:
    client-key: ${TOSS_CLIENT_KEY}
    secret-key: ${TOSS_SECRET_KEY}

member:
  service:
    base-url: ${MEMBER_SERVICE_BASE_URL}
