name: LP Auction CD

on:
  pull_request:
    types: [ opened, synchronize ] # PR 생성 시 및 test 브랜치에 새 커밋 푸시 시 실행
    branches: [ "common/feature/#191-cd_modify" ] # PR의 Target 브랜치
#    types: [ closed ]
#    branches: [ dev ]

jobs:
  check-deploy-condition:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    outputs:
      gateway_service_deploy: ${{ steps.check-deploy-label.outputs.gateway_service_deploy }}
      member_service_deploy: ${{ steps.check-deploy-label.outputs.member_service_deploy }}
    steps:
      - name: Check deploy label
        id: check-deploy-label
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            
            const hasGatewayServiceDeployLabel = pr.data.labels.map(label => label.name).includes("gateway-service-deploy");
            core.setOutput("gateway_service_deploy", hasGatewayServiceDeployLabel ? "true" : "false");
            
            const hasMemberServiceDeployLabel = pr.data.labels.map(label => label.name).includes("member-service-deploy");
            core.setOutput("member_service_deploy", hasMemberServiceDeployLabel ? "true" : "false");

      - name: Explain deploy decision
        run: |
          # gateway-service 배포 여부 체크
          if [[ "${{ steps.check-deploy-label.outputs.gateway_service_deploy }}" == "true" ]]; then
            echo "🚚 gateway-service 배포 작업을 진행합니다."
          else
            echo "✋ gateway-service 배포 작업을 진행하지 않습니다."
          fi
          
          # member-service 배포 여부 체크
          if [[ "${{ steps.check-deploy-label.outputs.member_service_deploy }}" == "true" ]]; then
            echo "🚚 member-service 배포 작업을 진행합니다."
          else
            echo "✋ member-service 배포 작업을 진행하지 않습니다."
          fi

  gateway-service-image-build:
    needs: [ check-deploy-condition ]
    if: needs.check-deploy-condition.outputs.gateway_service_deploy == 'true'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      gateway_service_image_build_result: ${{ steps.image-build-result.outputs.gateway_service_image_build_result }}
    continue-on-error: true
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew\

      - name: Build with gradle
        run: ./gradlew :gateway-service:bootJar -Pspring.profiles.active=prod --info

      - name: Login to Github Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Docker build & push
        id: docker-build-and-push
        working-directory: ./gateway-service
        run: |
          docker build --no-cache -f docker/Dockerfile --build-arg SPRINGBOOT_APP_PROFILE=prod --platform linux/amd64 -t ${{ secrets.GATEWAY_SERVICE_GHCR_IMAGE }}:${{ github.sha }} .
          docker push ${{ secrets.GATEWAY_SERVICE_GHCR_IMAGE }}:${{ github.sha }}

      - name: Set Image build result
        if: always()
        id: image-build-result
        run: |
          echo "gateway_service_image_build_result=fail" >> $GITHUB_OUTPUT
          if [[ ${{ steps.docker-build-and-push.outcome }} == "success" ]]; then
          echo "gateway_service_image_build_result=success" >> $GITHUB_OUTPUT
          fi

  member-service-image-build:
    needs: [ check-deploy-condition ]
    if: needs.check-deploy-condition.outputs.member_service_deploy == 'true'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      member_service_image_build_result: ${{ steps.image-build-result.outputs.member_service_image_build_result }}
    continue-on-error: true
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew\

      - name: Build with gradle
        run: ./gradlew :member-service:bootJar -Pspring.profiles.active=prod --info

      - name: Login to Github Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Docker build & push
        id: docker-build-and-push
        working-directory: ./member-service
        run: |
          docker build --no-cache -f docker/Dockerfile --build-arg SPRINGBOOT_APP_PROFILE=prod --platform linux/amd64 -t ${{ secrets.MEMBER_SERVICE_GHCR_IMAGE }}:${{ github.sha }} .
          docker push ${{ secrets.MEMBER_SERVICE_GHCR_IMAGE }}:${{ github.sha }}

      - name: Set Image build result
        if: always()
        id: image-build-result
        run: |
          echo "member_service_image_build_result=fail" >> $GITHUB_OUTPUT
          if [[ ${{ steps.docker-build-and-push.outcome }} == "success" ]]; then
          echo "member_service_image_build_result=success" >> $GITHUB_OUTPUT
          fi

  gateway-service-deploy:
    needs: [ gateway-service-image-build ]
    if: needs.gateway-service-image-build.outputs.gateway_service_image_build_result == 'success'
    runs-on: groovid-app-ec2-runner
    continue-on-error: true
    outputs:
      gateway_service_deploy_result: ${{ steps.deploy-result.outputs.gateway_service_deploy_result }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Login to Github Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Create secret file
        run: |
          cd ~/project
          
          sudo cat <<EOF > .env
          GATEWAY_SERVICE_IMAGE_REPOSITORY=${{ secrets.GATEWAY_SERVICE_GHCR_IMAGE }}
          GATEWAY_SERVICE_IMAGE_TAG=${{ github.sha }}
          
          MEMBER_SERVICE_IMAGE_REPOSITORY=${{ secrets.MEMBER_SERVICE_GHCR_IMAGE }}
          MEMBER_SERVICE_IMAGE_TAG=${{ github.sha }}
          EOF
          
          sudo cat <<EOF > .gateway-service-secret
          PORT_NUMBER=8080
          
          PRODUCT_SERVICE_URI=${{ secrets.PRODUCT_SERVICE_BASE_URL }}
          MEMBER_SERVICE_URI=${{ secrets.MEMBER_SERVICE_BASE_URL }}
          POINTWALLET_SERVICE_URI=${{ secrets.POINTWALLET_SERVICE_BASE_URL }}
          FULFILLMENT_SERVICE_URI=${{ secrets.FULFILLMENT_SERVICE_BASE_URL }}
          AUCTION_SERVICE_URI=${{ secrets.AUCTION_SERVICE_BASE_URL }}
          
          JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
          JWT_EXPIRATION_TIME=${{ secrets.JWT_EXPIRATION_TIME }}
          EOF

          if [ ! -f .member-service-secret ]; then
            touch .member-service-secret
          fi

      - name: Start new server application
        id: start-new-server-application
        run: |
          cd ~/project
          sudo docker-compose stop gateway-service
          sudo docker-compose rm -f gateway-service
          sudo docker-compose up -d gateway-service
          
          echo "🔍 gateway-service 헬스 체크 확인 중..."
          for i in {1..20}; do
            response=$(curl -s http://localhost:8080/gateway-service/actuator/health || true)
            if [[ "$response" == *'"status":"UP"'* ]]; then
              echo "🍺 gateway-service 정상 실행 확인!"
              exit 0
            else
              echo "⏳ gateway-service 실행 대기... ($i/20)"
              sleep 3
            fi
          done
          echo "❌ gateway-service가 60초 동안 정상 실행되지 않음..."
          exit 1

  member-service-deploy:
    needs: [ member-service-image-build ]
    if: needs.member-service-image-build.outputs.member_service_image_build_result == 'success'
    runs-on: groovid-app-ec2-runner
    continue-on-error: true
    outputs:
      member_service_deploy_result: ${{ steps.deploy-result.outputs.member_service_deploy_result }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Login to Github Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Create secret file
        run: |
          cd ~/project
          
          cat <<EOF > .env
          MEMBER_SERVICE_IMAGE_REPOSITORY=${{ secrets.MEMBER_SERVICE_GHCR_IMAGE }}
          MEMBER_SERVICE_IMAGE_TAG=${{ github.sha }}
          
          GATEWAY_SERVICE_IMAGE_REPOSITORY=${{ secrets.GATEWAY_SERVICE_GHCR_IMAGE }}
          GATEWAY_SERVICE_IMAGE_TAG=${{ github.sha }}
          EOF
          
          cat <<EOF > .member-service-secret
          PORT_NUMBER=8080
          DB_URL=${{ secrets.DB_URL }}
          DB_USER_NAME=${{ secrets.DB_USER_NAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          
          JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
          JWT_EXPIRATION_TIME=${{ secrets.JWT_EXPIRATION_TIME }}
          EOF

          if [ ! -f .gateway-service-secret ]; then
            touch .gateway-service-secret
          fi

      - name: Start new server application
        id: start-new-server-application
        run: |
          cd ~/project
          sudo docker-compose stop member-service
          sudo docker-compose rm -f member-service
          sudo docker-compose up -d member-service
          
          echo "🔍 member-service 헬스 체크 확인 중..."
          for i in {1..20}; do
            response=$(curl -s http://localhost:8081/member-service/actuator/health || true)
            if [[ "$response" == *'"status":"UP"'* ]]; then
              echo "🍺 member-service 정상 실행 확인!"
              exit 0
            else
              echo "⏳ member-service 실행 대기... ($i/20)"
              sleep 3
            fi
          done
          echo "❌ member-service가 60초 동안 정상 실행되지 않음..."
          exit 1

  cleanup-secret-files:
    needs: [ gateway-service-deploy, member-service-deploy ]
    if: |
      always() &&
      (needs.gateway-service-deploy.result != 'skipped' || needs.member-service-deploy.result != 'skipped')
    runs-on: groovid-app-ec2-runner
    steps:
      - name: Remove secret files from EC2 host
        run: |
          cd ~/project
          sudo rm -rf .env .gateway-service-secret .member-service-secret
          echo "🧹 민감 정보 파일(.env, secret)이 깔끔하게 정리되었습니다."
